
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (PROJECT)"
    message: |
      The target system is: Linux -  - 
      The host system is: Linux - 6.8.0-57-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (PROJECT)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /usr/bin/i586-alpine-linux-musl-c++ 
      Build flags: --sysroot=/home/build/sysroot-x86/;-Os;-fstack-clash-protection;-Wformat;-Werror=format-security;-D_GLIBCXX_ASSERTIONS=1;-D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1;-D_LIBCPP_ENABLE_HARDENED_MODE=1;-fno-plt
      Id flags:  
      
      The output was:
      1
      /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find libstdc++.so.6.0.33: No such file or directory
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (PROJECT)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/i586-alpine-linux-musl-c++ 
      Build flags: --sysroot=/home/build/sysroot-x86/;-Os;-fstack-clash-protection;-Wformat;-Werror=format-security;-D_GLIBCXX_ASSERTIONS=1;-D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1;-D_LIBCPP_ENABLE_HARDENED_MODE=1;-fno-plt
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        /home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/3.31.7/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "/usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (PROJECT)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "/home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-ABdhHb"
      binary: "/home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-ABdhHb"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "--sysroot=/home/build/sysroot-x86/ -Os -fstack-clash-protection -Wformat -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-plt"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "--sysroot=/home/build/sysroot-x86/ -Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-ABdhHb'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_5a1c5/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_5a1c5.dir/build.make CMakeFiles/cmTC_5a1c5.dir/build
        gmake[1]: Entering directory '/home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-ABdhHb'
        Building CXX object CMakeFiles/cmTC_5a1c5.dir/CMakeCXXCompilerABI.cpp.o
        /usr/bin/i586-alpine-linux-musl-c++   --sysroot=/home/build/sysroot-x86/ -Os -fstack-clash-protection -Wformat -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-plt    -v -o CMakeFiles/cmTC_5a1c5.dir/CMakeCXXCompilerABI.cpp.o -c /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp
        Using built-in specs.
        COLLECT_GCC=/usr/bin/i586-alpine-linux-musl-c++
        Target: i586-alpine-linux-musl
        Configured with: /home/build/aports/main/gcc/src/gcc-14.2.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=i586-alpine-linux-musl --enable-checking=release --disable-cet --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-languages=c,c++,ada --enable-link-serialization=2 --enable-linker-build-id --with-arch=pentium-m --with-fpmath=sse --with-tune=generic --enable-cld --disable-libquadmath --disable-libssp --disable-libsanitizer --disable-bootstrap --with-sysroot=/home/build/sysroot-x86 --enable-shared --enable-threads --enable-tls --disable-libgomp --disable-libatomic --disable-libitm --with-bugurl=https://gitlab.alpinelinux.org/alpine/aports/-/issues --with-system-zlib --with-linker-hash-style=gnu --with-pkgversion='Alpine 14.2.0'
        Thread model: posix
        Supported LTO compression algorithms: zlib
        gcc version 14.2.0 (Alpine 14.2.0) 
        COLLECT_GCC_OPTIONS='--sysroot=/home/build/sysroot-x86/' '-Os' '-fstack-clash-protection' '-Wformat=1' '-D' '_GLIBCXX_ASSERTIONS=1' '-D' '_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1' '-D' '_LIBCPP_ENABLE_HARDENED_MODE=1' '-fno-plt' '-v' '-o' 'CMakeFiles/cmTC_5a1c5.dir/CMakeCXXCompilerABI.cpp.o' '-c' '-shared-libgcc' '-mtune=generic' '-march=pentium-m' '-dumpdir' 'CMakeFiles/cmTC_5a1c5.dir/'
         /usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/cc1plus -quiet -v -isysroot /home/build/sysroot-x86/ -D_GNU_SOURCE -D _GLIBCXX_ASSERTIONS=1 -D _LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D _LIBCPP_ENABLE_HARDENED_MODE=1 /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp -quiet -dumpdir CMakeFiles/cmTC_5a1c5.dir/ -dumpbase CMakeCXXCompilerABI.cpp.cpp -dumpbase-ext .cpp -mtune=generic -march=pentium-m -Os -Wformat=1 -version -fstack-clash-protection -fno-plt -o /tmp/ccPeaoEc.s
        GNU C++17 (Alpine 14.2.0) version 14.2.0 (i586-alpine-linux-musl)
        	compiled by GNU C version 14.2.0, GMP version 6.3.0, MPFR version 4.2.1-p1, MPC version 1.3.1, isl version isl-0.26-GMP
        
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring nonexistent directory "/home/build/sysroot-x86/usr/local/include"
        ignoring nonexistent directory "/home/build/sysroot-x86/usr/include/fortify"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/include/c++/14.2.0
         /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/include/c++/14.2.0/i586-alpine-linux-musl
         /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/include/c++/14.2.0/backward
         /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/include
         /home/build/sysroot-x86/usr/include
         /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/include
        End of search list.
        Compiler executable checksum: e248f99c4ed277e711d6e3d72c823b1d
        COLLECT_GCC_OPTIONS='--sysroot=/home/build/sysroot-x86/' '-Os' '-fstack-clash-protection' '-Wformat=1' '-D' '_GLIBCXX_ASSERTIONS=1' '-D' '_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1' '-D' '_LIBCPP_ENABLE_HARDENED_MODE=1' '-fno-plt' '-v' '-o' 'CMakeFiles/cmTC_5a1c5.dir/CMakeCXXCompilerABI.cpp.o' '-c' '-shared-libgcc' '-mtune=generic' '-march=pentium-m' '-dumpdir' 'CMakeFiles/cmTC_5a1c5.dir/'
         /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/bin/as -v --32 -o CMakeFiles/cmTC_5a1c5.dir/CMakeCXXCompilerABI.cpp.o /tmp/ccPeaoEc.s
        GNU assembler version 2.44 (i586-alpine-linux-musl) using BFD version (GNU Binutils) 2.44
        COMPILER_PATH=/usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/:/usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/:/usr/libexec/gcc/i586-alpine-linux-musl/:/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/:/usr/lib/gcc/i586-alpine-linux-musl/:/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/bin/
        LIBRARY_PATH=/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/:/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/lib/:/home/build/sysroot-x86/lib/:/home/build/sysroot-x86/usr/lib/
        COLLECT_GCC_OPTIONS='--sysroot=/home/build/sysroot-x86/' '-Os' '-fstack-clash-protection' '-Wformat=1' '-D' '_GLIBCXX_ASSERTIONS=1' '-D' '_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1' '-D' '_LIBCPP_ENABLE_HARDENED_MODE=1' '-fno-plt' '-v' '-o' 'CMakeFiles/cmTC_5a1c5.dir/CMakeCXXCompilerABI.cpp.o' '-c' '-shared-libgcc' '-mtune=generic' '-march=pentium-m' '-dumpdir' 'CMakeFiles/cmTC_5a1c5.dir/CMakeCXXCompilerABI.cpp.'
        Linking CXX executable cmTC_5a1c5
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5a1c5.dir/link.txt --verbose=1
        /usr/bin/i586-alpine-linux-musl-c++ --sysroot=/home/build/sysroot-x86/ -Os -fstack-clash-protection -Wformat -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-plt  --sysroot=/home/build/sysroot-x86/ -Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs -v -Wl,-v CMakeFiles/cmTC_5a1c5.dir/CMakeCXXCompilerABI.cpp.o -o cmTC_5a1c5
        Using built-in specs.
        COLLECT_GCC=/usr/bin/i586-alpine-linux-musl-c++
        COLLECT_LTO_WRAPPER=/usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/lto-wrapper
        Target: i586-alpine-linux-musl
        Configured with: /home/build/aports/main/gcc/src/gcc-14.2.0/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=i586-alpine-linux-musl --enable-checking=release --disable-cet --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-languages=c,c++,ada --enable-link-serialization=2 --enable-linker-build-id --with-arch=pentium-m --with-fpmath=sse --with-tune=generic --enable-cld --disable-libquadmath --disable-libssp --disable-libsanitizer --disable-bootstrap --with-sysroot=/home/build/sysroot-x86 --enable-shared --enable-threads --enable-tls --disable-libgomp --disable-libatomic --disable-libitm --with-bugurl=https://gitlab.alpinelinux.org/alpine/aports/-/issues --with-system-zlib --with-linker-hash-style=gnu --with-pkgversion='Alpine 14.2.0'
        Thread model: posix
        Supported LTO compression algorithms: zlib
        gcc version 14.2.0 (Alpine 14.2.0) 
        COMPILER_PATH=/usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/:/usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/:/usr/libexec/gcc/i586-alpine-linux-musl/:/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/:/usr/lib/gcc/i586-alpine-linux-musl/:/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/bin/
        LIBRARY_PATH=/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/:/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/lib/:/home/build/sysroot-x86/lib/:/home/build/sysroot-x86/usr/lib/
        COLLECT_GCC_OPTIONS='--sysroot=/home/build/sysroot-x86/' '-Os' '-fstack-clash-protection' '-Wformat=1' '-D' '_GLIBCXX_ASSERTIONS=1' '-D' '_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1' '-D' '_LIBCPP_ENABLE_HARDENED_MODE=1' '-fno-plt' '--sysroot=/home/build/sysroot-x86/' '-v' '-o' 'cmTC_5a1c5' '-shared-libgcc' '-mtune=generic' '-march=pentium-m' '-dumpdir' 'cmTC_5a1c5.'
         /usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/collect2 -plugin /usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/lto-wrapper -plugin-opt=-fresolution=/tmp/ccJiGAPd.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --sysroot=/home/build/sysroot-x86/ --build-id --eh-frame-hdr --hash-style=gnu -m elf_i386 --as-needed -dynamic-linker /lib/ld-musl-i386.so.1 -pie -z now -o cmTC_5a1c5 /home/build/sysroot-x86/usr/lib/Scrt1.o /home/build/sysroot-x86/usr/lib/crti.o /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/crtbeginS.o -L/usr/lib/gcc/i586-alpine-linux-musl/14.2.0 -L/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/lib -L/home/build/sysroot-x86/lib -L/home/build/sysroot-x86/usr/lib --as-needed -O1 --sort-common -z pack-relative-relocs -v CMakeFiles/cmTC_5a1c5.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm -lssp_nonshared -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/crtendS.o /home/build/sysroot-x86/usr/lib/crtn.o
        collect2 version 14.2.0
        /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/bin/ld -plugin /usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/i586-alpine-linux-musl/14.2.0/lto-wrapper -plugin-opt=-fresolution=/tmp/ccJiGAPd.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --sysroot=/home/build/sysroot-x86/ --build-id --eh-frame-hdr --hash-style=gnu -m elf_i386 --as-needed -dynamic-linker /lib/ld-musl-i386.so.1 -pie -z now -o cmTC_5a1c5 /home/build/sysroot-x86/usr/lib/Scrt1.o /home/build/sysroot-x86/usr/lib/crti.o /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/crtbeginS.o -L/usr/lib/gcc/i586-alpine-linux-musl/14.2.0 -L/usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/lib -L/home/build/sysroot-x86/lib -L/home/build/sysroot-x86/usr/lib --as-needed -O1 --sort-common -z pack-relative-relocs -v CMakeFiles/cmTC_5a1c5.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm -lssp_nonshared -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/crtendS.o /home/build/sysroot-x86/usr/lib/crtn.o
        GNU ld (GNU Binutils) 2.44
        /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find libstdc++.so.6.0.33: No such file or directory
        collect2: error: ld returned 1 exit status
        gmake[1]: *** [CMakeFiles/cmTC_5a1c5.dir/build.make:102: cmTC_5a1c5] Error 1
        gmake[1]: Leaving directory '/home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-ABdhHb'
        gmake: *** [Makefile:134: cmTC_5a1c5/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (PROJECT)"
    checks:
      - "Check for working CXX compiler: /usr/bin/i586-alpine-linux-musl-c++"
    directories:
      source: "/home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-JKnNhd"
      binary: "/home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-JKnNhd"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "--sysroot=/home/build/sysroot-x86/ -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-plt"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "--sysroot=/home/build/sysroot-x86/ -Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs"
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-JKnNhd'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_b79ba/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_b79ba.dir/build.make CMakeFiles/cmTC_b79ba.dir/build
        gmake[1]: Entering directory '/home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-JKnNhd'
        Building CXX object CMakeFiles/cmTC_b79ba.dir/testCXXCompiler.cxx.o
        /usr/bin/i586-alpine-linux-musl-c++   --sysroot=/home/build/sysroot-x86/ -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-plt  -o CMakeFiles/cmTC_b79ba.dir/testCXXCompiler.cxx.o -c /home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-JKnNhd/testCXXCompiler.cxx
        Linking CXX executable cmTC_b79ba
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b79ba.dir/link.txt --verbose=1
        /usr/bin/i586-alpine-linux-musl-c++ --sysroot=/home/build/sysroot-x86/ -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fno-plt  --sysroot=/home/build/sysroot-x86/ -Wl,--as-needed,-O1,--sort-common -Wl,-z,pack-relative-relocs  CMakeFiles/cmTC_b79ba.dir/testCXXCompiler.cxx.o -o cmTC_b79ba
        /usr/lib/gcc/i586-alpine-linux-musl/14.2.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find libstdc++.so.6.0.33: No such file or directory
        collect2: error: ld returned 1 exit status
        gmake[1]: *** [CMakeFiles/cmTC_b79ba.dir/build.make:102: cmTC_b79ba] Error 1
        gmake[1]: Leaving directory '/home/build/chrona-packages/main/qastools/src/qastools-v0.23.0/CMakeFiles/CMakeScratch/TryCompile-JKnNhd'
        gmake: *** [Makefile:134: cmTC_b79ba/fast] Error 2
        
      exitCode: 2
...
